name: Checks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: 'true'

    - name: Check dictionary is alphabetical
      run: |
        awk 'match($0, /\[([^]]+)\]/, m) { print tolower(m[1]) "\t" $0 }' dictionary.md | LC_ALL=C sort -k1,1 -s -c
